apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-api
  namespace: items-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: items-api
  template:
    metadata:
      labels:
        app: items-api
    spec:
      containers:
        - name: items-api
          image: items-api:latest
          imagePullPolicy: Never   # Utilise l'image locale, ne va pas sur Docker Hub
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config   # Injecte DATABASE_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"