apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: items-app
spec:
  replicas: 1        # Une seule instance PostgreSQL
  selector:
    matchLabels:
      app: postgres  # Sélectionne les Pods avec ce label
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret  # Injecte les variables du Secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data  # Où PostgreSQL stocke ses données
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc  # Utilise notre PVC