apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: items-app
spec:
  accessModes:
    - ReadWriteOnce      # Un seul Pod peut lire/écrire à la fois
  resources:
    requests:
      storage: 1Gi       # On demande 1GB de stockage